### Create new Patient
POST http://localhost:4000/patients/registration
Content-Type: application/json

{
  "name": "Adam Smith",
  "email": "Adam12@gmail.com",
  "address": "No:15/A Main Street New York",
  "dateOfBirth": "1985-08-15",
  "registeredDate": "2025-03-27"
}

###